Instagram_clone/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('instagrams/', include('instagrams.urls', namespace='instagrams')),
    path('comments/', include('comments.urls', namespace='comments')),
    path('accounts/', include('django.contrib.auth.urls')),
]

if settings.DEBUG is True:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

comments/urls.py
from django.urls import path
from .views import (
    CommentDeleteView,
    CommentCreateAjaxView,
    CommentUpdateView
)
app_name = 'comments'

urlpatterns = [
    # 주의! 댓글을 create할 때는 댓글을 작성하려는 'Instagram'객체를 찾아야 하므로 feed_pk를 사용한다.
    path('create/<int:feed_pk>/', CommentCreateAjaxView.as_view(), name='comment-create'),
    # 나머지 경우 댓글 자체를 업데이트하거나 삭제하기 때문에 그대로 comment의 pk를 사용한다.
    path('update/<int:pk>/', CommentUpdateView.as_view(), name='comment-update'),
    path('delete/<int:pk>/', CommentDeleteView.as_view(), name='comment-delete'),
]

comments/models.py
from django.conf import settings
from django.db import models
from django.urls import reverse

from Instagram_clone.mixins import Postable, TimeStampedMixin


class Comment(Postable):
    instagram = models.ForeignKey('instagrams.Instagram',
                                  on_delete=models.CASCADE,
                                  related_name='comments',
                                  verbose_name='인스타그램')

    def get_absolute_url(self):
        # Instagram feed-list로 리다이렉트한다.
        return reverse('instagrams:feed-list')

comments/forms.py
from django.forms import ModelForm

from comments.models import Comment


class CommentForm(ModelForm):
    class Meta:
        model = Comment
        fields = ['content']

    def __init__(self, *args, **kwargs):
        super(CommentForm, self).__init__(*args, **kwargs)

        # 최대한 Instagram과 비슷하게 스타일링한다
        self.fields['content'].widget.attrs['class'] = 'textfield-comment'
        self.fields['content'].widget.attrs['placeholder'] = '댓글 달기...'
        self.fields['content'].label = ''
        # FIXME: 필요에 따라 Text필드가 너무 넓어보인다면 한줄로 제한한다.
        # self.fields['content'].widget.attrs['rows'] = 1

comments/views.py
from django.contrib.auth.mixins import LoginRequiredMixin
from django.http import HttpResponseRedirect
from django.shortcuts import get_object_or_404, render
from django.views.generic import (
    DeleteView,
    CreateView,
    UpdateView
)

from Instagram_clone.mixins import ValidAuthorRequiredMixin
from comments.models import Comment
from instagrams.models import Instagram


class CommentCreateAjaxView(LoginRequiredMixin, CreateView):
    # 댓글 내용과 분기점을 받아서 적절한 FK를 찾아 연결하고 댓글 목록을 AJAX로 업데이트한다.
    model = Comment
    fields = ['content']
    template_name = 'comments/comments_container.html'

    def form_valid(self, form):
        # 잠깐 db 저장을 멈춘다
        comment = form.save(commit=False)
        # 현재 request를 요청한 user를 댓글의 작성자로 넣어준다
        comment.author = self.request.user
        # 현재 댓글이 달릴 instagram 객체의 pk는 routing rule의 <int:feed_pk>로 넘어온다
        instagram = get_object_or_404(Instagram, pk=self.kwargs.get('feed_pk'))
        comment.instagram = instagram
        comment.save()

        context = {
            'comments': Comment.objects
                .select_related('author')
                .filter(instagram=instagram)
                .order_by('created')
        }

        return render(self.request, 'comments/comments_container.html', context)


class CommentUpdateView(ValidAuthorRequiredMixin, UpdateView):
    model = Comment
    template_name_suffix = '_update_form'
    fields = ['content']

    def get_success_url(self):
        # 현재 Comment의 absolute_url로 리다이렉트 한다.
        return Comment.objects.get(pk=self.kwargs['pk']).get_absolute_url()


class CommentDeleteView(ValidAuthorRequiredMixin, DeleteView):
    model = Comment

    def get_success_url(self):
        # 이전 페이지로 이동
        # POST request로 넘어온 'next'인자의 값을 읽어서 success_url로 던져준다
        to = self.request.POST.get('next', '/')
        return to

comments/templates/comments/comment_update_form.html
{% extends "index.html" %}
{% load crispy_forms_tags %}

{% block content %}
    <form method="post">
        {% csrf_token %}
        {{ form | crispy }}
        <input type="submit" class="btn btn-primary" value="수정"/>
    </form>
{% endblock %}

comments/templates/comments/comments_container.html
{% load static %}

{% for comment in comments.all %}
    <div class="comment {% if request.user == comment.author %} col-9 {% else %} col-12 {% endif %} text-left">
        <p>
            <b>{{ comment.author.username }}</b> &nbsp {{ comment.content }}
        </p>
    </div>
    {% if request.user == comment.author %}
        <div class="comment-button-container col-3 text-right">
            <form action="{% url 'comments:comment-delete' pk=comment.pk %}" method="post">
                {% csrf_token %}
                <input type="hidden" name="next" value="{{ request.path }}">
                <button class="btn comment-delete" onclick="return confirm('정말로 삭제합니까?');">삭제</button>
            </form>
            <form action="{% url 'comments:comment-update' pk=comment.pk %}" method="post">
                {% csrf_token %}
                <button class="btn comment-edit">수정</button>
            </form>
        </div>
    {% endif %}
{% endfor %}