Instagram_clone/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('instagrams/', include('instagrams.urls', namespace='instagrams')),
    path('comments/', include('comments.urls', namespace='comments')),
    path('accounts/', include('django.contrib.auth.urls')),
]

if settings.DEBUG is True:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

comments/urls.py
from django.urls import path
from .views import (
    CommentDeleteView,
    CommentCreateAjaxView,
    CommentUpdateView
)
app_name = 'comments'

urlpatterns = [
    # 주의! 댓글을 create할 때는 댓글을 작성하려는 'Instagram'객체를 찾아야 하므로 feed_pk를 사용한다.
    path('create/<int:feed_pk>/', CommentCreateAjaxView.as_view(), name='comment-create'),
    # 나머지 경우 댓글 자체를 업데이트하거나 삭제하기 때문에 그대로 comment의 pk를 사용한다.
    path('update/<int:pk>/', CommentUpdateView.as_view(), name='comment-update'),
    path('delete/<int:pk>/', CommentDeleteView.as_view(), name='comment-delete'),
]

instagrams/urls.py
from django.urls import path

from .views import (
    InstagramDeleteView,
    InstagramCreateView,
    InstagramListView,
    InstagramUpdateView
)

app_name = 'instagrams'

urlpatterns = [
    path('', InstagramListView.as_view(), name='feed-list'),
    path('create/', InstagramCreateView.as_view(), name='feed-create'),
    path('update/<int:pk>/', InstagramUpdateView.as_view(), name='feed-update'),
    path('delete/<int:pk>/', InstagramDeleteView.as_view(), name='feed-delete'),
]

instagrams/models.py
from datetime import datetime, timedelta
from io import BytesIO

from PIL import Image, ExifTags
from django.conf import settings
from django.core.files.base import ContentFile
from django.db import models

# 인스타그램 사진을 업로드하면 저장할 경로를 지정한다
from django.utils import timezone
from django.utils.timezone import now

from Instagram_clone.mixins import TimeStampedMixin, Postable


def get_instagram_photo_path(instance, filename):
    return 'media/feed/{:%Y/%m/%d}/{}'.format(now(), filename)


def rotate_and_resize(photo):
    # 저장시 가로 최고 길이는 614px이다.
    base = 614
    photo = Image.open(photo)
    photo_format = photo.format

    # exif 태그를 검색하여 사진의 회전여부를 판단한다.
    try:
        for orientation in ExifTags.TAGS.keys():
            if ExifTags.TAGS[orientation] == 'Orientation':
                break
        exif = dict(photo._getexif().items())

        if exif[orientation] == 3:
            photo = photo.rotate(180, expand=True)
        elif exif[orientation] == 6:
            photo = photo.rotate(270, expand=True)
        elif exif[orientation] == 8:
            photo = photo.rotate(90, expand=True)
    except (AttributeError, KeyError, IndexError):
        # 사진에 exif 태그가 없으면 그대로 진행한다.
        pass
    # 회전 컨트롤이 완료된 이미지의 크기를 얻는다.
    (width, height) = photo.size

    # 사진이 작든 크든 너비를 614px로 맞추기 위한 비율을 구한다.
    factor = base / width

    # 너비와 높이를 해당 factor를 곱하여 계산한다.
    photo = photo.resize((int(width * factor), int(height * factor)), Image.ANTIALIAS)
    photo_io = BytesIO()
    photo.save(photo_io, photo_format, quality=60)
    return photo_io


class Instagram(Postable):
    @property
    def timedelta_string(self):
        # settings에서 Timezone을 'Asia/Seoul'로 변경했을 경우 now()는 로컬타임이지만 DB에 저장된 객체들의 시간은 UTC이다.
        # 차이값을 구하기위해 timezone을 맞춰준다. 이 때 datetime의 timezone이 아닌 django.utils의 timezone을 사용한다.
        delta = datetime.now(tz=timezone.utc) - self.created

        if delta < timedelta(minutes=1):
            return str(delta.seconds) + ' 초 전'
        elif delta < timedelta(hours=1):
            return str(int(delta.seconds / 60)) + ' 분 전'
        elif delta < timedelta(days=1):
            return str(int(delta.seconds / 3600)) + ' 시간 전'
        elif delta < timedelta(days=7):
            # 날짜만 따로 빼서 날짜간의 차이를 계산한 후 리턴한다.
            delta = datetime.now(tz=timezone.utc).date() - self.created.date()
            return str(delta.days) + ' 일 전'
        else:
            # settings.py에 변경한 로컬 시간대를 기준으로 UTC 시간을 변환하여 리턴한다.
            return timezone.localtime(self.created, timezone.get_current_timezone())


class InstagramPhoto(TimeStampedMixin):
    photo = models.ImageField(upload_to=get_instagram_photo_path, verbose_name='사진')
    instagram = models.ForeignKey('instagrams.Instagram',
                                  on_delete=models.CASCADE,
                                  related_name='photos',
                                  verbose_name='인스타그램')

    def save(self, *args, **kwargs):
        photo_io = rotate_and_resize(self.photo)
        self.photo.save(self.photo.name, ContentFile(photo_io.getvalue()), save=False)
        # 직접 인스턴스의 save를 불러서 파일을 저장한다.
        super(InstagramPhoto, self).save(*args, **kwargs)

instagrams/forms.py
from django.forms import ModelForm, forms, ClearableFileInput

from instagrams.models import Instagram


class InstagramForm(ModelForm):
    class Meta:
        model=Instagram
        fields=['content']

    # 여러개의 FileInput을 허용하는 새로운 'images'필드를 정의한다.
    images = forms.FileField(widget=ClearableFileInput(attrs={'multiple': True}), label='사진')

instagrams/views.py
from django.contrib.auth.mixins import LoginRequiredMixin
from django.db.models import Case, When
from django.shortcuts import render

# Create your views here.
from django.urls import reverse_lazy
from django.views.generic import DeleteView, ListView
from django.views.generic.edit import FormMixin, CreateView, UpdateView

from Instagram_clone.mixins import ValidAuthorRequiredMixin
from comments.forms import CommentForm
from instagrams.forms import InstagramForm
from instagrams.models import Instagram, InstagramPhoto


class InstagramCreateView(LoginRequiredMixin, CreateView):
    model = Instagram
    form_class = InstagramForm
    success_url = reverse_lazy('instagrams:feed-list')

    def form_valid(self, form):
        # 잠깐 save를 막고 현재 user를 author로 넣어준다
        instagram = form.save(commit=False)
        instagram.author = self.request.user
        instagram.save()

        # 만일 requst로 FILE이 넘어온다면 InstagramPhoto로 간주하고 객체들을 생성한다
        if self.request.FILES:
            # forms.py에서 images라는 이름으로 FileField를 정의했음을 기억한다
            for f in self.request.FILES.getlist('images'):
                feed_photo = InstagramPhoto(instagram=instagram, photo=f)
                feed_photo.save()
        # 수퍼클래스의 form_valid 구현을 따로 수정할 필요는 없다.
        return super(InstagramCreateView, self).form_valid(form)


class InstagramListView(LoginRequiredMixin, FormMixin, ListView):
    form_class = CommentForm
    paginate_by = 20
    template_name = 'instagrams/feed_list.html'

    def get_context_data(self, **kwargs):
        # superclass의 get_context_data를 부른다
        context = super(InstagramListView, self).get_context_data(**kwargs)
        # CommentForm을 context_data에 넣어준다
        context['comment_form'] = self.get_form()
        return context

    def get_queryset(self):
        # Instagram 객체들을 가져오는데 FK를 모조리 join하여 가져온다.
        # 1. Reverse relationship을 join해서 가져오기 위해 2번의 prefetch_related를 한다
        # 2. 마지막으로 단순 FK를 join해서 가져오기 위해 1번의 select_related를 한다
        # 3. 최신 객체가 가장 위에 올라와야 하고 그다음으로는 최근 수정된 순으로 객체를 뿌려줘야 한다.
        queryset = Instagram.objects \
            .prefetch_related('photos') \
            .prefetch_related('comments__author') \
            .select_related('author') \
            .order_by('-created', '-updated')
        return queryset


class InstagramUpdateView(ValidAuthorRequiredMixin, UpdateView):
    model = Instagram
    form_class = InstagramForm
    success_url = reverse_lazy('instagrams:feed-list')

    def form_valid(self, form):
        instance = form.save()
        # 현재 인스타그램과 연결된 사진들을 삭제하고 다시 만들어준다.
        InstagramPhoto.objects.filter(instagram=instance).delete()
        if self.request.FILES:
            for f in self.request.FILES.getlist('images'):
                feed_photo = InstagramPhoto(instagram=instance, photo=f)
                feed_photo.save()

        return super(InstagramUpdateView, self).form_valid(form)


class InstagramDeleteView(ValidAuthorRequiredMixin, DeleteView):
    model = Instagram
    success_url = reverse_lazy('instagrams:feed-list')

instagrams/templates/instagrams/feed_list.html
{% extends "index.html" %}
{% load static %}
{% load crispy_forms_tags %}

{% block style-head %}
    <link rel="stylesheet" type="text/css" href="{% static 'instagrams/css/feed_list_style.css' %}">
{% endblock %}

{% block content %}
    {# 최상위 컨테이너  #}
    <div class="instagram-container">
        {% for instagram in object_list %}

            {# 각 instagram을 실질적으로 나타낼 div #}
            <div class="card">
                {# Bootstrap내장 container를 사용한다#}
                <div class="container">
                    {# 1. 첫번째 row: 단순히 작성자 정보를 나타낸다. #}
                    <div class="row">
                        <div class="col-9">
                            <span>{{ instagram.author.username }}</span>
                        </div>
                        <div class="col-3 text-right">
                            {# 드롭다운 옵션들을 넣어줄 컨테이너 #}
                            <div class="dropdown-options">
                                {# 먼저 아이콘을 뿌려준다. #}
                                <i class="fas fa-ellipsis-v"></i>
                                <div class="dropdown-content text-center">
                                    {# 수정하기는 단순히 수정 view로 리다이렉트한다 #}
                                    <a href="{% url 'instagrams:feed-update' instagram.pk %}">수정하기</a>
                                    {# 삭제하기는 아예 form으로 넘겨서 삭제 확인창 없이 한번에 처리한다. #}
                                    <form action="{% url 'instagrams:feed-delete' instagram.pk %}" method="post">{% csrf_token %}
                                        {# 어디서 많이 본 패턴이다. #}
                                        <input type="hidden" name="next" value="{{ request.path }}">
                                        <input type="submit" onclick="return confirm('정말 삭제하시겠습니까?')" class="delete-instagram btn-link" value="삭제하기">
                                    </form>
                                </div>
                            </div>
                        </div>
                    </div>
                    {# 2. 2번째 row: 업로드한 사진들이 들어간다. #}
                    {# TODO: Add Carousel #}
                    <div class="photo-container row">
                        {% for instagram_photo in instagram.photos.all %}
                            <div class="photo-carousel">
                                <img src="{{ instagram_photo.photo.url }}"/>
                            </div>
                        {% endfor %}
                    </div>
                    {# 3. 3번째 row: 말풍선 모양 버튼들이 들어간다. 추후 좋아요 등을 구현하면 여기에 넣는다.  #}
                    <div class="button-container row">
                        <button class="add-comment-balloon"><i class="far fa-comment"></i></button>
                    </div>
                    {# 4. 4번째 row: 업로더 정보가 한번 더 나타나고 내용이 들어간다. #}
                    <div class="description-container row">
                        <div class="content-container col-12"><b>{{ instagram.author.username }}</b> &nbsp; {{ instagram.content }}</div>
                    </div>
                    {# 5. 5번째 row: 현재 인스타그램에 달린 댓글들이 포함된다다. #}
                    <div class="comment-container-div row">
                        {% include 'comments/comments_container.html' with comments=instagram.comments %}
                    </div>
                    {# 6. 6번째 row: instagram 작성 시간이 현재시간과의 '시간차'로 나타난다. #}
                    <div class="created-time row">
                        <div class="col-12">{{ instagram.timedelta_string }}</div>
                    </div>
                    {# 7. 7번째 row: 댓글 입력 form이 들어간다#}
                    <div class="comment-creator-div row" >
                        <div class="comments-form col-12">
                            <form action="{% url 'comments:comment-create' feed_pk=instagram.pk %}" method="post">{% csrf_token %}
                                {{ comment_form | crispy }}
                                <input type="hidden" name="next" value="{{ request.path }}">
                                <input class="input-comment-create" style="display: none;" type="submit" class="btn btn-secondary"/>
                            </form>
                        </div>
                    </div>
                </div>
            </div>

        {% endfor %}
    </div>
{% endblock %}

{% block javascript %}
    <script type="text/javascript" src="{% static 'instagrams/js/feed_list_js.js' %}"></script>
{% endblock %}

instagrams/templates/instagrams/instagram_form.html
{% extends "index.html" %}
{% load crispy_forms_tags %}

{% block content %}
    <form method="post" enctype="multipart/form-data">
        {% csrf_token %}
        {{ form | crispy }}
        <input type="submit" class="btn btn-primary" value="올리기"/>
    </form>
{% endblock %}